version: "3.8"

services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    hostname: db

  app:
    build:
      context: app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_NAME=codetest
      - DB_PORT=3306
      - DB_DIALECT=mysql+pymysql
    ports:
      - 8888:8888
    volumes:
      - ./app:/app
    working_dir: /app
    stdin_open: true
    tty: true
